### ISSUE TITLE
I see an app.json, but why no "deploy to heroku" button in README ?

### ISSUE THREAD

**Issue by aahnik** [alenpaul2001/Web-Screenshot-Bot#16]

**Comment by alenpaulvarghese** [comment]
Due to the recent surge in useless/personal-use clones of telegram open source bots. I decided to remove the deploy button to avoid such behaviors. Why? cause if we keep abusing their free service, Heroku will force themselves to remove the free plan which will affect many telegram developers including me.

**Comment by aahnik** [comment]
I am amazed. You have a great vision. You are wise indeed.
